version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "./app/build.gradle.kts"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gradle"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "github-actions"
