name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Services pour exécuter Xvfb en mode headless
    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    env:
      DISPLAY: ":99.0"  # Set display for Xvfb to avoid GUI issues in headless environment

    steps:
    - uses: actions/checkout@v4

    # Configuration du JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configuration de Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.10'

    # Lancer Xvfb avant de démarrer les tests
    - name: Start Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

    # Construction du projet avec Gradle
    - name: Build with Gradle
      run: gradle build

    # Publier le rapport des tests comme artefact
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: app/build/reports/tests/test/index.html

    # Étape pour exécuter l'analyse PMD
    - name: Run PMD Analysis
      uses: pmd/pmd-github-action@v2  # Utiliser la version correcte
      with:
        rulesets: 'ruleset.xml'
        max-violations: 10
        format: "html"
        output-file: "pmd-report.html"  

    # Optionnel : Publier le rapport PMD en tant qu'artefact
    - name: Upload PMD report
      uses: actions/upload-artifact@v4
      with:
        name: pmd-report
        path: pmd.html

