name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.10'

    # Build the project using Gradle without relying on the Gradle Wrapper
    - name: Build with Gradle
      run: gradle build

    # Publish test results as an artifact
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: build/test-results/test

  # Removed the dependency-submission job as per instructions

